In [93]:
import pandas as pd
import requests

url = 'https://esa.un.org/unpd/wup/Download/Files/WUP2018-F18-Total_Population_Annual.xls'
df1 = pd.read_excel(url, sheet_name = 0)
df1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,United Nations,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Population Division,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Department of Economic and Social Affairs,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
#change the header
pop = df1.iloc[14:]
pop2.columns = pop.iloc[0]

#drop the header row
pop3 = pop2.drop(pop2.index[[0]])
pop3.rename(columns={pop3.columns[3]: 'code' ,'Region, subregion, country or area': 'country'}, inplace=True)
pop3

14,Index,country,Note,code,1950,1951.0,1952.0,1953.0,1954.0,1955.0,...,2041.0,2042.0,2043.0,2044.0,2045.0,2046.0,2047.0,2048.0,2049.0,2050.0
16,2,More developed regions,a,901,814865,824212.665,834074.389,844263.515,854631.777,865069.444,...,1297774.840,1297994.139,1298159.433,1298276.382,1298349.044,1298382.202,1298376.623,1298327.412,1298226.562,1298068.585
17,3,Less developed regions,b,902,1.72141e+06,1759604.121,1796509.995,1832966.843,1869670.691,1907173.091,...,7973288.433,8032851.751,8091496.496,8149178.267,8205860.528,8261526.993,8316168.817,8369766.020,8422299.417,8473754.168
18,4,Least developed countries,c,941,195259,199052.136,202904.860,206885.020,211045.058,215421.063,...,1648390.597,1677916.857,1707547.911,1737266.944,1767059.061,1796910.693,1826811.700,1856754.484,1886733.520,1916741.581
19,5,"Less developed regions, excluding least develo...",d,934,1.52615e+06,1560551.985,1593605.135,1626081.823,1658625.633,1691752.028,...,6324897.836,6354934.894,6383948.585,6411911.323,6438801.467,6464616.300,6489357.117,6513011.536,6535565.897,6557012.587
20,6,"Less developed regions, excluding China",NaN,948,1.1572e+06,1179836.180,1203955.385,1229495.321,1256404.335,1284636.948,...,6527110.247,6591093.225,6654437.857,6717104.821,6779059.707,6840278.198,6900741.972,6960429.596,7019321.437,7077398.224
21,7,High-income countries,e,1503,672896,680630.360,688858.965,697440.327,706262.038,715241.145,...,1277386.656,1278960.400,1280411.217,1281751.220,1282990.054,1284135.482,1285190.367,1286154.310,1287024.014,1287798.294
22,8,Middle-income countries,e,1517,1.73448e+06,1772394.343,1808889.488,1844730.274,1880558.365,1916892.378,...,6799701.843,6833596.524,6866497.698,6898369.077,6929181.568,6958928.067,6987607.372,7015202.952,7041697.383,7067079.456
23,9,Upper-middle-income countries,e,1502,956204,980195.343,1001876.475,1022053.675,1041402.171,1060465.450,...,2803615.816,2804050.615,2804032.671,2803544.699,2802573.826,2801123.429,2799198.932,2796792.151,2793892.527,2790495.775
24,10,Lower-middle-income countries,e,1501,778277,792199.000,807013.013,822676.599,839156.194,856426.928,...,3996086.027,4029545.909,4062465.027,4094824.378,4126607.742,4157804.638,4188408.440,4218410.801,4247804.856,4276583.681
25,11,Low-income countries,e,1500,128097,129969.107,131991.799,134194.006,136593.546,139196.080,...,1190287.421,1214574.038,1239005.190,1263566.348,1288244.470,1313027.345,1337905.256,1362870.257,1387915.798,1413033.996
26,12,Sub-Saharan Africa,f,947,179621,183039.180,186625.519,190377.650,194295.351,198379.925,...,1814721.903,1852962.577,1891492.323,1930288.654,1969331.030,2008600.249,2048080.309,2087757.329,2127619.105,2167651.879
27,13,AFRICA,NaN,903,228670,233277.049,238113.121,243177.791,248471.497,253995.025,...,2142034.032,2184052.732,2226331.727,2268843.050,2311561.326,2354463.822,2397531.544,2440746.939,2484094.200,2527556.761
28,14,Eastern Africa,NaN,910,66758.3,68208.356,69711.520,71272.418,72895.738,74585.806,...,748102.425,763390.171,778762.361,794211.036,809728.865,825308.700,840944.270,856629.804,872359.868,888128.562
29,15,Burundi,NaN,108,2308.92,2359.123,2403.511,2445.420,2487.390,2531.184,...,20885.948,21403.341,21928.513,22460.525,22998.539,23542.141,24090.950,24644.319,25201.545,25762.044
30,16,Comoros,NaN,174,159.459,163.139,166.541,169.752,172.853,175.903,...,1282.209,1302.467,1322.720,1342.933,1363.098,1383.200,1403.227,1423.170,1443.013,1462.735
31,17,Djibouti,NaN,262,62.001,63.306,64.750,66.269,67.872,69.589,...,1245.401,1253.614,1261.491,1269.036,1276.268,1283.179,1289.766,1296.038,1301.978,1307.615
32,18,Eritrea,NaN,232,1142.15,1159.798,1179.537,1201.124,1224.384,1249.193,...,8300.073,8447.599,8594.901,8741.756,8887.988,9033.461,9178.086,9321.828,9464.689,9606.664
33,19,Ethiopia,NaN,231,18128,18466.968,18819.700,19184.292,19560.016,19947.292,...,168714.421,171271.652,173809.294,176325.273,178817.639,181284.897,183725.643,186137.980,188519.926,190869.632
34,20,Kenya,NaN,404,6076.76,6240.163,6412.363,6593.109,6782.287,6979.931,...,82723.272,84156.324,85585.822,87011.808,88434.154,89852.235,91265.247,92672.520,94073.394,95467.137
35,21,Madagascar,NaN,450,4083.55,4168.386,4256.770,4348.720,4444.288,4543.542,...,45283.723,46206.441,47135.665,48071.248,49012.988,49960.619,50913.785,51872.127,52835.205,53802.574
36,22,Malawi,NaN,454,2953.87,3008.067,3065.034,3124.734,3187.173,3252.332,...,34602.300,35373.855,36150.880,36932.805,37719.155,38509.466,39303.412,40100.768,40901.375,41705.002
37,23,Mauritius,1,480,493.255,506.433,521.188,537.047,553.626,570.648,...,1265.448,1261.389,1257.038,1252.432,1247.598,1242.572,1237.352,1231.995,1226.541,1221.030
38,24,Mayotte,NaN,175,15.141,15.728,16.443,17.249,18.094,18.985,...,428.032,435.713,443.368,450.985,458.543,466.059,473.509,480.897,488.235,495.498
39,25,Mozambique,NaN,508,6152.24,6248.717,6352.584,6463.088,6579.634,6701.749,...,55725.109,57019.852,58326.750,59645.171,60974.587,62314.434,63664.382,65024.388,66394.596,67774.943
40,26,RÃ©union,NaN,638,248.11,259.295,268.486,276.526,284.080,291.658,...,1001.399,1003.824,1005.966,1007.823,1009.419,1010.731,1011.789,1012.598,1013.183,1013.561
41,27,Rwanda,NaN,646,2186.18,2250.677,2313.311,2378.445,2448.825,2525.527,...,19364.953,19661.478,19954.727,20244.161,20529.380,20810.047,21086.028,21357.305,21623.956,21886.077
42,28,Seychelles,NaN,690,36.325,36.881,37.437,37.964,38.455,38.909,...,98.131,98.061,97.972,97.855,97.721,97.553,97.359,97.145,96.909,96.643
43,29,Somalia,NaN,706,2264.08,2307.673,2351.929,2397.159,2443.625,2491.520,...,28868.760,29602.596,30347.355,31102.953,31869.275,32646.129,33433.209,34230.143,35036.488,35851.792
44,30,South Sudan,NaN,728,2582.93,2601.651,2625.126,2653.097,2685.325,2721.544,...,21598.427,22009.951,22423.660,22839.397,23257.015,23676.336,24097.135,24519.204,24942.321,25366.221
45,31,Uganda,NaN,800,5158.19,5308.668,5455.540,5601.239,5748.208,5898.835,...,85721.545,87860.635,90021.613,92203.851,94406.655,96629.120,98870.311,101129.434,103405.702,105698.201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,244,Saint Pierre and Miquelon,NaN,666,4.571,4.603,4.633,4.660,4.691,4.723,...,7.234,7.258,7.283,7.295,7.315,7.323,7.338,7.352,7.367,7.379
259,245,United States of America,NaN,840,158804,160905.035,163324.851,165988.190,168827.613,171783.842,...,375734.948,377359.928,378950.342,380514.372,382058.853,383587.662,385102.864,386607.164,388102.725,389591.663
260,246,OCEANIA,NaN,909,12647.8,12971.297,13275.573,13572.461,13870.902,14176.713,...,53041.157,53506.858,53969.622,54429.598,54886.722,55341.136,55792.571,56240.340,56683.514,57121.455
261,247,Australia/New Zealand,NaN,927,10085.3,10360.535,10613.768,10857.134,11099.673,11347.299,...,36535.233,36802.180,37067.936,37332.804,37596.921,37860.452,38123.192,38384.384,38643.008,38898.302
262,248,Australia,25,36,8177.34,8412.604,8620.970,8816.902,9011.190,9210.908,...,31009.076,31252.803,31496.058,31739.106,31982.056,32225.028,32467.814,32709.660,32949.581,33186.818
263,249,New Zealand,NaN,554,1908,1947.931,1992.798,2040.232,2088.483,2136.391,...,5526.157,5549.377,5571.878,5593.698,5614.865,5635.424,5655.378,5674.724,5693.427,5711.484
264,250,Melanesia,NaN,928,2165.34,2203.567,2244.826,2288.858,2335.445,2384.384,...,15084.436,15276.644,15467.429,15656.615,15844.125,16029.795,16213.639,16395.672,16575.929,16754.472
265,251,Fiji,NaN,242,288.988,296.209,304.814,314.351,324.482,334.976,...,996.089,997.158,998.019,998.661,999.087,999.293,999.277,999.088,998.711,998.190
266,252,New Caledonia,NaN,540,64.825,64.256,64.408,65.126,66.278,67.748,...,354.449,357.188,359.877,362.528,365.137,367.695,370.220,372.700,375.126,377.509
267,253,Papua New Guinea,NaN,598,1674.04,1702.370,1731.230,1761.050,1792.140,1824.712,...,12394.461,12563.656,12731.778,12898.700,13064.330,13228.568,13391.391,13552.789,13712.784,13871.403
268,254,Solomon Islands,NaN,90,89.794,91.809,94.077,96.560,99.215,102.024,...,918.279,931.433,944.506,957.477,970.329,983.052,995.652,1008.125,1020.497,1032.777
269,255,Vanuatu,NaN,548,47.697,48.923,50.297,51.771,53.330,54.924,...,421.158,427.209,433.249,439.249,445.242,451.187,457.099,462.970,468.811,474.593
270,256,Micronesia,NaN,954,155.095,158.150,161.223,164.332,167.560,170.908,...,632.305,635.488,638.534,641.472,644.227,646.855,649.343,651.717,653.983,656.179
271,257,Guam,NaN,316,59.651,60.262,60.877,61.471,62.053,62.641,...,189.701,190.193,190.640,191.042,191.410,191.729,192.003,192.245,192.456,192.647
272,258,Kiribati,NaN,296,33.048,33.623,34.286,35.007,35.777,36.596,...,161.147,163.017,164.902,166.808,168.697,170.593,172.479,174.360,176.230,178.085
273,259,Marshall Islands,NaN,584,13.001,13.222,13.438,13.624,13.784,13.894,...,62.454,63.028,63.547,64.033,64.457,64.825,65.154,65.424,65.659,65.868
274,260,Micronesia (Fed. States of),NaN,583,32.001,33.408,34.600,35.693,36.777,37.893,...,124.958,125.391,125.798,126.179,126.546,126.894,127.234,127.559,127.878,128.193
275,261,Nauru,NaN,520,2.954,3.057,3.194,3.337,3.481,3.619,...,11.518,11.507,11.491,11.481,11.461,11.441,11.415,11.397,11.363,11.337
276,262,Northern Mariana Islands,NaN,580,6.999,7.081,7.215,7.409,7.674,8.010,...,55.939,55.642,55.324,54.981,54.599,54.201,53.784,53.354,52.916,52.469
277,263,Palau,NaN,585,7.441,7.497,7.613,7.791,8.014,8.255,...,26.588,26.710,26.832,26.948,27.057,27.172,27.274,27.378,27.481,27.580
278,264,Polynesia,NaN,957,241.999,249.045,255.756,262.137,268.224,274.122,...,789.183,792.546,795.723,798.707,801.449,804.034,806.397,808.567,810.594,812.502
279,265,American Samoa,NaN,16,18.94,19.296,19.540,19.677,19.729,19.702,...,57.901,57.832,57.748,57.650,57.526,57.396,57.247,57.094,56.927,56.759
280,266,Cook Islands,NaN,184,15.077,15.410,15.643,15.844,16.071,16.372,...,17.952,17.953,17.959,17.956,17.955,17.955,17.951,17.940,17.939,17.945
281,267,French Polynesia,NaN,258,60.266,62.085,63.870,65.593,67.252,68.854,...,320.739,321.569,322.323,323.008,323.632,324.183,324.659,325.075,325.434,325.713
282,268,Niue,NaN,570,4.667,4.678,4.684,4.686,4.685,4.694,...,1.749,1.755,1.757,1.762,1.759,1.768,1.774,1.776,1.784,1.786
283,269,Samoa,NaN,882,82.097,84.437,86.819,89.238,91.696,94.208,...,231.575,233.170,234.694,236.152,237.530,238.830,240.055,241.210,242.305,243.371
284,270,Tokelau,NaN,772,1.566,1.517,1.504,1.521,1.559,1.607,...,1.508,1.510,1.519,1.524,1.534,1.540,1.547,1.555,1.555,1.562
285,271,Tonga,NaN,776,47.22,49.315,51.170,52.783,54.150,55.323,...,132.874,133.812,134.714,135.575,136.387,137.164,137.901,138.595,139.268,139.926
286,272,Tuvalu,NaN,798,5.166,5.220,5.293,5.371,5.473,5.569,...,13.834,13.917,14.000,14.084,14.158,14.246,14.329,14.413,14.496,14.580
287,273,Wallis and Futuna Islands,NaN,876,7,7.087,7.233,7.424,7.609,7.793,...,11.051,11.028,11.009,10.996,10.968,10.952,10.934,10.909,10.886,10.860

In [95]:
#get columns
col = pop2.columns.get_values()
col2 = col.tolist()
del col2[:5]
col2

[1951.0,
 1952.0,
 1953.0,
 1954.0,
 1955.0,
 1956.0,
 1957.0,
 1958.0,
 1959.0,
 1960.0,
 1961.0,
 1962.0,
 1963.0,
 1964.0,
 1965.0,
 1966.0,
 1967.0,
 1968.0,
 1969.0,
 1970.0,
 1971.0,
 1972.0,
 1973.0,
 1974.0,
 1975.0,
 1976.0,
 1977.0,
 1978.0,
 1979.0,
 1980.0,
 1981.0,
 1982.0,
 1983.0,
 1984.0,
 1985.0,
 1986.0,
 1987.0,
 1988.0,
 1989.0,
 1990.0,
 1991.0,
 1992.0,
 1993.0,
 1994.0,
 1995.0,
 1996.0,
 1997.0,
 1998.0,
 1999.0,
 2000.0,
 2001.0,
 2002.0,
 2003.0,
 2004.0,
 2005.0,
 2006.0,
 2007.0,
 2008.0,
 2009.0,
 2010.0,
 2011.0,
 2012.0,
 2013.0,
 2014.0,
 2015.0,
 2016.0,
 2017.0,
 2018.0,
 2019.0,
 2020.0,
 2021.0,
 2022.0,
 2023.0,
 2024.0,
 2025.0,
 2026.0,
 2027.0,
 2028.0,
 2029.0,
 2030.0,
 2031.0,
 2032.0,
 2033.0,
 2034.0,
 2035.0,
 2036.0,
 2037.0,
 2038.0,
 2039.0,
 2040.0,
 2041.0,
 2042.0,
 2043.0,
 2044.0,
 2045.0,
 2046.0,
 2047.0,
 2048.0,
 2049.0,
 2050.0]

In [96]:
pop3.head()

14,Index,country,Note,code,1950,1951.0,1952.0,1953.0,1954.0,1955.0,...,2041.0,2042.0,2043.0,2044.0,2045.0,2046.0,2047.0,2048.0,2049.0,2050.0
16,2,More developed regions,a,901,814865,824212.665,834074.389,844263.515,854631.777,865069.444,...,1297774.840,1297994.139,1298159.433,1298276.382,1298349.044,1298382.202,1298376.623,1298327.412,1298226.562,1298068.585
17,3,Less developed regions,b,902,1.72141e+06,1759604.121,1796509.995,1832966.843,1869670.691,1907173.091,...,7973288.433,8032851.751,8091496.496,8149178.267,8205860.528,8261526.993,8316168.817,8369766.020,8422299.417,8473754.168
18,4,Least developed countries,c,941,195259,199052.136,202904.860,206885.020,211045.058,215421.063,...,1648390.597,1677916.857,1707547.911,1737266.944,1767059.061,1796910.693,1826811.700,1856754.484,1886733.520,1916741.581
19,5,"Less developed regions, excluding least develo...",d,934,1.52615e+06,1560551.985,1593605.135,1626081.823,1658625.633,1691752.028,...,6324897.836,6354934.894,6383948.585,6411911.323,6438801.467,6464616.300,6489357.117,6513011.536,6535565.897,6557012.587
20,6,"Less developed regions, excluding China",NaN,948,1.1572e+06,1179836.180,1203955.385,1229495.321,1256404.335,1284636.948,...,6527110.247,6591093.225,6654437.857,6717104.821,6779059.707,6840278.198,6900741.972,6960429.596,7019321.437,7077398.224

In [106]:
#convert to longform
pop4 = pd.melt(pop3, id_vars=['code', 'country'], value_vars=list(col2))
pop5 = pop4.rename(columns={14: 'year'})
pop5.head()

  code                                            country  year        value
0  901                             More developed regions  1951   824212.665
1  902                             Less developed regions  1951  1759604.121
2  941                          Least developed countries  1951   199052.136
3  934  Less developed regions, excluding least develo...  1951  1560551.985
4  948            Less developed regions, excluding China  1951  1179836.180

In [109]:
#export to CSV
pop5.to_csv('soc.076_Nat_pop_long')